### ISSUE TITLE
Update readthedocs config

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#585]
We are getting a RTD build error about a missing "build.os" in the config. Apparently we need to strike the python.version entry here:

https://github.com/pysb/pysb/blob/9921446cc8869e27e8a2dcbe168056b4736c15a7/.readthedocs.yaml#L17

And add a block like this at the top level:

```yaml
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
```
